services:
  service-in-scala:
    status:
      url: "http://scala/ping"
      expected-code: "200"
      expected-response: "pong"
    health-url: "http://scala.com"
  service-in-java:
    status:
      url: "http://localhost:4567/"
      expected-code: "200"
      expected-response: "pong"
    health-url: "http://java.com"
  service-in-go:
    status:
      url: "http://go/ping"
      expected-code: "200"
      expected-response: "health"
    health-url: "http://go.com"
