services:
  service-in-scala:
    status:
      url: "http://scala.com/ping"
      expected-code: "200"
      expected-response: "pong"
    health-url: "http://scala.com"
  service-in-java:
    status:
      url: "http://java.com/ping"
      expected-code: "200"
      expected-response: "ok"
    health-url: "http://java.com"
  service-in-go:
    status:
      url: "http://go.com/ping"
      expected-code: "200"
      expected-response: "ok"
    health-url: "http://go.com"
